---
jobs:
  - name: scan
    public: true
    plan:
    - get: infrastructure-repo
      trigger: true
    - task: terraform-format
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: hashicorp/terraform, tag: "light"}
        inputs:
          - name: infrastructure-repo
        run:
          path: sh
          args: ["infrastructure-repo/ci/scripts/format.sh"]
    - task: tflint
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: wata727/tflint, tag: "latest"}
        inputs:
          - name: infrastructure-repo
        run:
          path: sh
          args: ["infrastructure-repo/ci/scripts/scan.sh"]

  - name: build
    public: true
    serial_groups: [version]
    plan:
      - get: vault
        params:
          paths:
            - aws/therasec-stage/sts/aws-global-admin
            - aws/therasec-prod/sts/aws-global-admin
      - get: infrastructure-repo
        passed: ["scan"]
        trigger: true
      - get: version
        params: {pre: rc}
      - task: get-credentials
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: digitalgenius/alpine-jq-git, tag: "latest"}
          inputs:
          - name: vault
          outputs:
          - name: aws-creds
          run:
            path: sh
            args: ["infrastructure-repo/ci/scripts/get_aws_credentials.sh"]
      - task: build
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: hashicorp/terraform, tag: "light"}
          inputs:
            - name: aws-creds
            - name: infrastructure-repo
            - name: version
          outputs:
            - name: terraform-plan-out
          run:
            path: sh
            args: ["infrastructure-repo/ci/scripts/build.sh"]
      - put: infrastructure-repo-artifacts
        params: {file: terraform-plan-out/terraform-plan-*.tgz}
      - put: version
        params: {file: version/number}

  - name: provision
    public: true
    serial_groups: [version]
    plan:
      - get: infrastructure-repo
        passed: ["build"]
      - get: infrastructure-repo-artifacts
        passed: ["build"]
      - get: version
        params: {bump: final}
      - task: provision
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: hashicorp/terraform, tag: "light"}
          inputs:
            - name: infrastructure-repo
            - name: infrastructure-repo-artifacts
            - name: version
          outputs:
            - name: release
          run:
            path: sh
            args: ["infrastructure-repo/ci/scripts/provision.sh"]
      - put: version
        params: { bump: final }
      - put: release
        params:
          name: release/name
          tag:  release/tag

  - name: bump-major
    serial_groups: [version]
    plan:
    - put: version
      params: {bump: major}

  - name: bump-minor
    serial_groups: [version]
    plan:
    - put: version
      params: {bump: minor}

  - name: bump-patch
    serial_groups: [version]
    plan:
    - get: version
      passed: [provision]
      trigger: true
    - put: version
      params: {bump: patch, pre: rc}


resources:
- name: infrastructure-repo
  type: git
  source:
    uri: ((github-uri))
    branch: master
    private_key: ((github-private-key))

- name: version
  type: semver
  source:
    driver: git
    initial_version: 0.0.1
    uri: ((github-uri))
    branch: version
    file: version
    private_key: ((github-private-key))

- name: infrastructure-repo-artifacts
  type: s3
  source:
    bucket: terraform-pipeline-rc
    regexp: terraform-plan-(.*).tgz
    access_key_id: ((s3-access-key-id))
    secret_access_key: ((s3-secret-access-key))

- name: release
  type: github-release
  source:
    owner: ((github-org))
    repository: ((github-repo))
    access_token: ((github-access-token))

- name: vault
  type: vault
  source:
    url: ((vault-addr))
    auth_method: AppRole
    role_id: ((vault-role-id))
    secret_id: ((vault-secret-id))

resource_types:
  - name: vault
    type: docker-image
    source:
      repository: docurated/concourse-vault-resource
      tag: latest
